const appname = "eMart Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password?",
    anyProblem = "In case of any difficulty, contact administration",
    dashboard = "Dashboard",
    rating = "Rating",
    unpaid = "Unpaid",
    shopSettings = "Edit Account",
    logout = "Logout",
    messages = "Messages",
    editProfile = "Edit Profile",
    editshopProfile = " Edit Account",
    totalSale = "Total Sales",
    popular = "Popular Products",
    orders = "Orders",
    loginTo = "Shop Login",
    products = "Products",
    settings = "Setting",
    featured = "Featured",
    edit = "Edit",
    save = "Save",
    confirmPass = "Confirm Password",
    changeImage = "Change Image",
    remove = "Remove",
    name = "Username",
    chat = "Chat",
    credit = "@BabaDevs",
    review = "Reviews";
const aboutaccount = "About Account", aboutyou = "About You";

//Edit account
const address = 'Address :',
city = 'City :',
state = 'State / Province :',
postal = 'Postal / Zip code :';

